$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$failures = 0

function Pass($message) {
    Write-Host "PASS: $message"
}

function Fail($path, $line, $rule, $message) {
    $script:failures++
    if ($line) {
        Write-Host "FAIL: $path`:$line - $rule - $message"
    } else {
        Write-Host "FAIL: $path - $rule - $message"
    }
}

function Check-FilePattern($relativePath, $pattern, $rule, $message) {
    $path = Join-Path $root $relativePath
    if (-not (Test-Path $path -PathType Leaf)) {
        Fail $relativePath $null "required-file" "File does not exist."
        return
    }

    $lines = Get-Content $path
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match $pattern) {
            Fail $relativePath ($i + 1) $rule $message
        }
    }
}

Write-Host "PHASE 10 SECURITY VERIFICATION"

# Backend must use BCrypt.
$bcrypt = Join-Path $root "backend/src/main/java/com/matrimony/auth/BCryptPasswordHasher.java"
if ((Test-Path $bcrypt) -and (Get-Content $bcrypt -Raw) -match "BCryptPasswordEncoder") {
    Pass "Backend password hashing uses BCrypt"
} else {
    Fail "backend/src/main/java/com/matrimony/auth/BCryptPasswordHasher.java" $null `
        "password-hashing" "BCryptPasswordEncoder was not found."
}

# Session lookup must use token hashes rather than raw token persistence.
$sessionRepo = Join-Path $root "backend/src/main/java/com/matrimony/auth/SessionRepository.java"
if ((Test-Path $sessionRepo) -and (Get-Content $sessionRepo -Raw) -match "token_hash") {
    Pass "Session repository uses token_hash persistence"
} else {
    Fail "backend/src/main/java/com/matrimony/auth/SessionRepository.java" $null `
        "session-token-storage" "token_hash persistence was not found."
}

# Authentication filter must derive identity from the authenticated session.
$filter = Join-Path $root "backend/src/main/java/com/matrimony/auth/AuthAuthenticationFilter.java"
if ((Test-Path $filter) -and (Get-Content $filter -Raw) -match "Authorization" -and (Get-Content $filter -Raw) -match "sessionService") {
    Pass "Backend authentication filter validates Bearer sessions"
} else {
    Fail "backend/src/main/java/com/matrimony/auth/AuthAuthenticationFilter.java" $null `
        "authentication-filter" "Bearer/session validation was not found."
}

# Logout must revoke the authenticated session.
$authController = Join-Path $root "backend/src/main/java/com/matrimony/auth/AuthController.java"
if ((Test-Path $authController) -and (Get-Content $authController -Raw) -match "sessionService\.revoke") {
    Pass "Logout revokes the authenticated session"
} else {
    Fail "backend/src/main/java/com/matrimony/auth/AuthController.java" $null `
        "session-revocation" "Logout does not visibly revoke the authenticated session."
}

# Android token protection.
$tokenStore = Join-Path $root "android/app/src/main/java/com/matrimonyapp/core/security/SecureTokenStore.kt"
$tokenContent = if (Test-Path $tokenStore) { Get-Content $tokenStore -Raw } else { "" }

if ($tokenContent -match "AndroidKeyStore") {
    Pass "Android token store uses AndroidKeyStore"
} else {
    Fail "android/app/src/main/java/com/matrimonyapp/core/security/SecureTokenStore.kt" $null `
        "token-protection" "AndroidKeyStore was not found."
}

if ($tokenContent -match "AES/GCM/NoPadding") {
    Pass "Android token store uses AES/GCM encryption"
} else {
    Fail "android/app/src/main/java/com/matrimonyapp/core/security/SecureTokenStore.kt" $null `
        "token-encryption" "AES/GCM/NoPadding was not found."
}

# Authorization header must be generated by the Android API client.
$apiClient = Join-Path $root "android/app/src/main/java/com/matrimonyapp/data/remote/ApiClient.kt"
$apiContent = if (Test-Path $apiClient) { Get-Content $apiClient -Raw } else { "" }

if ($apiContent -match 'header\("Authorization",\s*"Bearer') {
    Pass "Android API client sends Bearer Authorization"
} else {
    Fail "android/app/src/main/java/com/matrimonyapp/data/remote/ApiClient.kt" $null `
        "authorization-header" "Bearer Authorization header was not found."
}

# 401 must clear authentication state.
if ($apiContent -match 'response\.code == 401' -and $apiContent -match 'clear') {
    Pass "Android API client handles 401 by clearing authentication"
} else {
    Fail "android/app/src/main/java/com/matrimonyapp/data/remote/ApiClient.kt" $null `
        "unauthorized-handling" "401 handling with authentication clearing was not found."
}

# No dangerous TLS bypasses.
Get-ChildItem (Join-Path $root "backend/src/main/java") -Recurse -File -Include *.java | ForEach-Object {
    $relative = $_.FullName.Substring($root.Length + 1)
    Check-FilePattern $relative `
        'TrustAll|trustAll|ALLOW_ALL|X509TrustManager|HostnameVerifier\s*\{|setHostnameVerifier' `
        "tls-security" "Potential trust-all or TLS verification bypass."
}

Get-ChildItem (Join-Path $root "android/app/src/main/java") -Recurse -File -Include *.kt | ForEach-Object {
    $relative = $_.FullName.Substring($root.Length + 1)
    Check-FilePattern $relative `
        'TrustAll|trustAll|ALLOW_ALL|X509TrustManager|HostnameVerifier\s*\{|setHostnameVerifier' `
        "tls-security" "Potential trust-all or TLS verification bypass."
}

# No password/token/Authorization logging.
Get-ChildItem (Join-Path $root "backend/src/main/java") -Recurse -File -Include *.java | ForEach-Object {
    $relative = $_.FullName.Substring($root.Length + 1)
    Check-FilePattern $relative `
        '(?i)(log|logger)\.\w+\([^)]*(password|token|authorization)' `
        "secret-logging" "Potential password, token, or Authorization logging."
}

# No hardcoded common local/production password assignments in source.
Get-ChildItem (Join-Path $root "backend/src/main/java") -Recurse -File -Include *.java | ForEach-Object {
    $relative = $_.FullName.Substring($root.Length + 1)
    Check-FilePattern $relative `
        '(?i)(password|passwd|secret)\s*=\s*["''][^"'']+["'']' `
        "hardcoded-credential" "Possible hardcoded credential or secret assignment."
}

# Startup must read the Android animator duration scale and contain no Thread.sleep.
Get-ChildItem (Join-Path $root "android/app/src/main/java/com/matrimonyapp/ui/startup") -Recurse -File -Include *.kt | ForEach-Object {
    $relative = $_.FullName.Substring($root.Length + 1)
    Check-FilePattern $relative `
        'Thread\.sleep' `
        "startup-blocking" "Thread.sleep is forbidden in startup code."
}

$startupScreen = Join-Path $root "android/app/src/main/java/com/matrimonyapp/ui/startup/StartupScreen.kt"
if ((Test-Path $startupScreen) -and
    (Get-Content $startupScreen -Raw) -match "Settings\.Global\.ANIMATOR_DURATION_SCALE") {
    Pass "Startup screen reads Settings.Global.ANIMATOR_DURATION_SCALE"
} else {
    Fail "android/app/src/main/java/com/matrimonyapp/ui/startup/StartupScreen.kt" $null `
        "reduced-motion" "Settings.Global.ANIMATOR_DURATION_SCALE was not found."
}

if ($failures -eq 0) {
    Write-Host "PHASE 10 SECURITY VERIFICATION: PASS"
    exit 0
}

Write-Host "PHASE 10 SECURITY VERIFICATION: FAIL ($failures failure(s))"
exit 1